<link rel="apple-touch-icon" href="{{asset('/core/assets/images/apple-touch-icon.png')}}">
<link rel="shortcut icon" href="{{asset('/core/assets/images/favicon.ico')}}">
<!-- Stylesheets -->
<link rel="stylesheet" href="{{asset('core/global/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('core/global/css/bootstrap-extend.min.css')}}">
<link rel="stylesheet" href="{{asset('/core/assets/css/site.min.css')}}">
<link rel="stylesheet" href="{{asset('css/custom.css')}}">
<!-- Plugins -->
<link rel="stylesheet" href="{{asset('core/global/vendor/animsition/animsition.css')}}">
<link rel="stylesheet" href="{{asset('core/global/vendor/asscrollable/asScrollable.css')}}">
<link rel="stylesheet" href="{{asset('core/global/vendor/switchery/switchery.css')}}">
<link rel="stylesheet" href="{{asset('core/global/vendor/intro-js/introjs.css')}}">
<link rel="stylesheet" href="{{asset('core/global/vendor/slidepanel/slidePanel.css')}}">
<link rel="stylesheet" href="{{asset('core/global/vendor/flag-icon-css/flag-icon.css')}}">
<link rel="stylesheet" href="{{asset('core/global/vendor/waves/waves.css')}}">
<link rel="stylesheet" href="{{asset('/core/assets/examples/css/pages/errors.css')}}">
<!-- Fonts -->
<link rel="stylesheet" href="{{asset('core/global/fonts/material-design/material-design.min.css')}}">
<link rel="stylesheet" href="{{asset('core/global/fonts/brand-icons/brand-icons.min.css')}}">
<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>